### ISSUE TITLE
推特看到 就来试试了  发现报错了

### ISSUE THREAD

**Issue by declanchiu** [antfu/log-editor#1]
node_modules/log-editor/dist/index.mjs:2:8: error: No matching export in "browser-external:fs" for import "promises"
    2 │ import {promises as fs} from "fs";
      ╵         ~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/log-editor/dist/index.mjs:2:8: error: No matching export in "browser-external:fs" for import "promises"
    at failureErrorWithLog (/Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:1449:15)
    at /Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:1129:7)
    at /Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:1236:14
    at /Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/coderq/Desktop/My-Code/react/react17-Test/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by antfu** [comment]
It only works in Node.js environment as documented.

**Comment by declanchiu** [comment]
Sorry, I subscribed to you on Twitter and when log-editor appeared, I immediately went to use it, so I didn't see the documentation 🙈
